version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../simplest-PWA-web-application:/usr/share/nginx/html/pwa-web-app
      - ../monitoring_start_page:/usr/share/nginx/html/monitoring_start_page
      - ./nginx/pwa-web-app.conf:/etc/nginx/conf.d/pwa-web-app.conf
      - ./nginx/monitoring_start_page.conf:/etc/nginx/conf.d/monitoring_start_page.conf
      - ./nginx/xwiki.conf:/etc/nginx/conf.d/xwiki.conf
    # restart: always
    networks:
      - xwiki-docker-compose_xwiki-bridge
networks:
  xwiki-docker-compose_xwiki-bridge:
    external: true