version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../simplest-PWA-web-application:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    # restart: always